### ISSUE TITLE
clicking on error message should jump to the respective line in editor.

### ISSUE THREAD

**Issue by bwagner** [jwdj/EasyABC#14] opened 2019-10-10 19:46 UTC
clicking on error message should jump to the respective line in editor.
(EasyABC Version 1.3.5 on OS X 10.14.6 Mojave)

**Comment by jwdj** [comment] 2021-07-22 19:12
Since version 1.3.5 is quite old I will close this issue. If the problem is still present in the current version (1.3.7.8) please supply a way to reproduce the error.

**Closed by jwdj** 2021-07-22 19:12 UTC
